version: 2
jobs:
########################## INIT ########################
  init:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      - JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Dependencies RELEASE
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
          - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
############################################## AMBIENTE RELEASE #############################################################################
  release:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      - JVM_OPTS: -Xmx3200m
    steps:
      - checkout
       #Restauro Caches
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies RELEASE
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
          - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
       #Ejecutos Test y guardo el reporte de resultado
      - run:
          name: Run Tests RELEASE
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports   
      #Creo el Apk y la guardo como artefacto
      - run:
          name: Run Build RELEASE
          command: ./gradlew :app:assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: artifact-file
      - store_test_results:
          path: app/build/test-results
############################################## AMBIENTE DEBUG ############################################################################# 
  debug:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      - JVM_OPTS: -Xmx3200m
    steps:
      - checkout
        #Restauro Caches
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies DEBUG
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
          - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #Ejecutos Test y guardo el reporte de resultado
      - run:
          name: Run Tests DEBUG
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports   
      #Creo el Apk y la guardo como artefacto
      - run:
          name: Run Build DEBUG
          command: ./gradlew :app:assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
      - store_test_results:
          path: app/build/test-results
############################################## CONFIGURACION RAMAS #############################################################################
workflows:
  version: 2
  workflow:
    jobs:
    - release:
          filters:
            branches:
              only: master
    - debug:
          filters:
            branches:
              only: develop
