version: 2
jobs:
  release:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-27-alpha
    environment:
    - JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - run:
         name: download key RELEASE
         shell: /bin/sh
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Download Dependencies RELEASE
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
     - run:
         name: Run Tests RELEASE
         command: ./gradlew lint test
    - store_artifacts:
        path: app/build/reports
        destination: reports   
    - run:
         name: Run Build RELEASE
         command: ./gradlew :app:assembleRelease
    - store_artifacts:
         path: app/build/outputs/apk/release/
         destination: artifact-file
    - store_test_results:
        path: app/build/test-results
    - run:
         name: Deploy Owncloud Repositories RELEASE
         shell: /bin/sh
         command: sh /home/circleci/code/.circleci/release.sh
        
  debug:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-27-alpha
    environment:
    - JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Download Dependencies DEBUG
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Run Tests DEBUG
        command: ./gradlew lint test
    - store_artifacts:
        path: app/build/reports
        destination: reports   
    - run:
         name: Run Build DEBUG
         command: ./gradlew :app:assembleDebug
    - store_artifacts:
         path: app/build/outputs/apk/debug/
         destination: artifact-file
    - store_test_results:
        path: app/build/test-results
    - run:
         name: Deploy Owncloud Repositories DEBUG
         shell: /bin/sh
         command: sh /home/circleci/code/.circleci/debug.sh
workflows:
  version: 2
  workflow:
    jobs:
    - release:
          filters:
            branches:
              only: master
    - debug:
          filters:
            branches:
              only: desarrollo
